### ISSUE TITLE
Review Bare 1 tom 5

### ISSUE THREAD

**Issue by SamuelGraden** [Decending/E7020E_tasks#11]
# Bare 1
Vi får lika svar, snyggt jobbat ser inga konstigheter

# Bare 2
Snyggt jobbat allt ser bra ut

#Bare 3
Olika Diff på 3.3, vet inte varför dock, skillnaden var inte markant. 

# Bare 4
Ser bra ut

# Bare 5
Set också bra ut.

# Övrigt
Varför kör ni Github? Spelar ju ingen roll, reflekterade bara på det.

**Comment by Decending** [comment]
Övrigt:
Det är vad jag är van vid, finns det någon fördel med att köra gitlab istället?
