### ISSUE TITLE
review

### ISSUE THREAD

**Issue by albgal-0** [Decending/E7020E_tasks#12]
In general it's all pretty good!
First of all I have seen that in bare 1, on line 259 they say there is no 0x08000f28 .. 0x08000f38, but looking at row 232-237 there is. 
You are missing to do the "Document each low-level access code by the appropriate section in the datasheet." in bare4! :)

**Comment by Decending** [comment]
Yeah, I missed that.
Thank you for the feedback!

**Comment by Decending** [comment]
For some reason I thought this part should be from my run of the code:
0x08000f28 .. 0x08000f38
