### ISSUE TITLE
Bare 6-9

### ISSUE THREAD

**Issue by 01joja** [Decending/E7020E_tasks#13]
## Bare 6

0:

```Rust
//    `rcc.cfgr.sysclk(84.mhz()).pclk1(42.mhz()).pclk2(64.mhz()).freeze();`
//
//    ** My answer here **
//    the pclk1 and pclk2 configurations (42 and 64) doesn't seem to be compatible with the sysclk.
//    The pclk1 and pclk2 clock speeds need to be sysclk / (1 or 2 or 4 or 8 or 16) to be compatible.
```

This worked for us. Have you tried to run it? It might be true what you are saying but it still works.

4:

```Rust
//    ** My answer here **
//    5.4V, this seems like a bit much.
//    We get 4.4V if we disconnect the ground. 
```

I agree. But we got 4.9 V. The most intreating part is that we are driving the MCU with 3.3V.

6:

I think [this](https://controllerstech.com/rgb-led-and-stm32/) explains it a bit. I'm still not 100% sure of how it exactly works.

```Rust
//    ** My answer here **
//    It flashes the LED really fast, which is weird, according to STM32cubeMX
//    these settings hould be incompatible.
//    We can't get any measurements from the board, which was the expected outcome,
//    but it's a bit weird that there is no panic.
```
I think Tommy got it to work in the "Cube". But he had to fiddle with it for a lite while. I can't say if it's correct to run or not.

## Bare 7

Looks good.

## Bare 8

```Rust
//    What did you receive in `moserial`?
//
//    ** My answer here **
//    abcd
//
//    What do you receive in the RTT terminal?
//
//    ** My answer here **
//    Ok 97
//    Ok 98
//    Ok 99
//    Ok 100
//
//    What do you believe to be the problem?
//
//    Hint: Look at the code in `idle` what does it do?
//
//    ** My answer here **
//    There doesn't seem to be a problem...
```

This is really strange. I had a problem and Carls and Ottos group also had a problem.

## Bare 9

I had no problems with creating error. But this may come from that you don't run it in VS code. I don't really know.

**Comment by Decending** [comment]
Regarding 0:
The clock speeds will be incompatable, but I think the hardware will default to some value or do somefunny business which results in behaviour that we don't specify, it doesn't necessarily mean that we don't get something similar to what we specified in the code.

**Comment by Decending** [comment]
Regarding 6:
I think that it's intuitive that it's running, in a sense. Some value will be in the scaler spot, so regardless of the sysclock we should get some value, just not the one we specified. "Something else happens" since the hardware is not smart, and the compiler can't find any error in the code so it compiles and runs it since it has no idea of the limitations of the hardware.
