### ISSUE TITLE
Review bare 6-9

### ISSUE THREAD

**Issue by ka11i0** [Decending/E7020E_tasks#14]
bare6: Bra, but no pictures :(
bare7: Looks good.
bare8: Good
bare9: To make the communication completely indestructible we made a separate task for printing with lowest priority. This works good since prints steals a lot of resources from the important communication! But if yours works fine then ok. :)

Total score: 5

**Comment by Decending** [comment]
Regarding bare6:
We've added the pictures now, was a slip up on our part.
